# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_false', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tf_question',
            options={'ordering': ['category'], 'verbose_name': 'Pytanie prawda/fałsz', 'verbose_name_plural': 'Pytania prawda/fałsz'},
        ),
        migrations.AlterField(
            model_name='tf_question',
            name='correct',
            field=models.BooleanField(default=False, help_text='Zaznacz jeśli odpowiedź jest prawdziwa. Zostaw pole puste jeśli jest fałszywa.', verbose_name='Prawda'),
        ),
    ]
