# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'News', 'verbose_name_plural': 'Newsy'},
        ),
    ]
