# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay_question',
            options={'verbose_name': 'Pytanie otwarte', 'verbose_name_plural': 'Pytania otwarte'},
        ),
    ]
