# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('docfile', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_opublikowania', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_opublikowania', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('docfile', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_opublikowania', models.DateTimeField(blank=True, null=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artykuly.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artykuly.Category'),
        ),
    ]
