# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Odpowiedź', 'verbose_name_plural': 'Odpowiedzi'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Pytanie testowe', 'verbose_name_plural': 'Pytania testowe'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Wpisz tekst odpowiedzi, który ma zostać wyświetlony', max_length=1000, verbose_name='Odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Czy to jest poprawna odpowiedź?', verbose_name='Prawda'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichoice.MCQuestion', verbose_name='Pytanie'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'brak')], help_text='Kolejność w jakiej możliwe opcje odpowiedzi są wyświetlane użytkownikowi.', max_length=30, null=True, verbose_name='Kolejność odpowiedzi'),
        ),
    ]
